- name: Install Python
  apt:
    name: python3
    state: present

- name: Update/upgrade packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install Node.js, npm, and pm2
  apt:
    name: 
      - nodejs
      - npm
  environment:
    NODE_OPTIONS: "--max_old_space_size=4096" # Increase memory limit for npm
  tags: 
    - frontend