version: 2.1
orbs:
  slack: circleci/slack@4.12.5

commands:
  destroy-environment:
    description: Destroy back-end and front-end CloudFormation stacks given a workflow ID.
    parameters:
      workflow-id:
        description: Workflow ID to identify the CloudFormation stacks.
        type: string
        default: "${CIRCLE_WORKFLOW_ID:0:7}"  # Default to first 7 characters of workflow ID
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |

            # Delete backend stack if it was created
            aws cloudformation delete-stack --stack-name udapeople-backend-<<parameters.workflow-id>>
            
            # Delete frontend stack if it was created
            aws cloudformation delete-stack --stack-name udapeople-frontend-<<parameters.workflow-id>>
            
            # Exit with a failure status
            exit 1


jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [test-frontend]
      - run:
          name: Test frontend
          command: |
            cd frontend
            npm install
            npm run test
  test-backend:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys: [test-backend]
      - run:
          name: Test backend
          command: |
            cd backend
            npm install
            npm run test
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
      - slack/notify:
          event: fail
          mentions: "@amit sharma"
          template: basic_fail_1
  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [scan-frontend]
      - run:
          name: Scan frontend
          command: |
            cd frontend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit fix --force
            npm audit --audit-level=critical
  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [scan-backend]
      - run:
          name: Scan backend
          command: |
            cd backend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit fix --force
            npm audit --audit-level=critical
  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli  # Replace with the Docker image that supports AWS CLI
    steps:
      - checkout  # Checkout code from Git
      - run:
          name: Install tar and gzip
          command: yum install -y tar gzip
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
              --tags project=udapeople
      - run:
          name: Ensure front-end infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
              --tags project=udapeople
      - run:
          name: Add back-end IP to Ansible inventory
          command: |
            # Fetch EC2 instance IP
            INSTANCE_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-*" --query "Reservations[].Instances[].PublicIpAddress" --output text)
            echo "[web]" > ~/project/ansible/inventory.txt
            echo "$INSTANCE_IP" >> ~/project/ansible/inventory.txt
            cat ~/project/ansible/inventory.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - ./project/ansible/inventory.txt  
      # Destroy environment on failure
      - destroy-environment:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}
  configure-infrastructure:
    docker:
      - image: python:3.11-rc-alpine # Docker image that supports Ansible
    steps:
      - checkout  # Checkout code from git

      # Add SSH key fingerprint to the job
      - add_ssh_keys:
          fingerprints:
            - "e3:02:15:88:cb:84:1d:a0:3d:f3:63:1d:b5:97:36:e9"

      # Attach workspace to the job
      - attach_workspace:
          at: ~/workspace

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            # Install necessary dependencies
            apk add ansible gzip openssh-client

      # Configure server
      - run:
          name: Configure server
          command: |
            # Run the Ansible playbook against the EC2 instance
            cat ~/workspace/project/ansible/inventory.txt
            pwd
            ls -la
            ansible-playbook ansible/configure-server.yml -i ~/workspace/project/ansible/inventory.txt -vvvv
      - destroy-environment:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}
  run-migrations:
    docker:
      - image: node:14 
    steps:
      - checkout
      - restore_cache:
            keys: [backend-build]
      - run:
          name: Run migrations
          command: |
            cd backend/src
            npm install
            ## Run and save the migration output
            npm run migrations > migrations_dump.txt
            cat migrations_dump.txt

      - run:
          name: Send migration results to memstash
          command: |
            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
            then
              curl --insecure https://kvdb.io/${KVDB_TOKEN}/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d 'success'
            fi
      
      - destroy-environment:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7} 
  deploy-frontend:
    docker:
      - image: circleci/node:13.8.0 
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Get backend url
          command: |
            export BACKEND_IP=$(aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --filters Name=tag:aws:cloudformation:stack-name,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} \
              --output text)
            export API_URL="http://${BACKEND_IP}:3030"
            echo "API_URL = ${API_URL}"
            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
            cat frontend/.env
      - run:
          name: Deploy frontend objects
          command: |
            cd frontend
            npm install
            npm run build
            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
      - destroy-environment:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}                         
  deploy-backend:
    docker:
      - image: python:3.11-rc-alpine 
    steps:
      - checkout
      - add_ssh_keys:
            fingerprints: ["e3:02:15:88:cb:84:1d:a0:3d:f3:63:1d:b5:97:36:e9"]
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys: [backend-deploy]
      - run:
            name: Install Dependencies
            command: |
              apk add --update --no-cache tar gzip curl nodejs npm aws-cli ansible
      - run:
          name: Deploy backend
          command: |
            cd backend
            npm install
            npm run build
            cd ..
            tar -C backend -czvf artifact.tar.gz .
            mkdir -p ~/project/ansible/roles/deploy/files/
            mv artifact.tar.gz ansible/roles/deploy/files/artifact.tar.gz
            ansible-playbook ansible/deploy-backend.yml -i ~/workspace/project/ansible/inventory.txt -vvvv
      - destroy-environment:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}
  smoke-test:
    docker:
      - image: alpine:latest  # Use a lightweight Docker image
    steps:
      - checkout  # Checkout code from Git
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache curl nodejs npm
      - run:
          name: Get backend URL
          command: |
            export BACKEND_IP=$(cat backend_ip.txt)  # Assuming you saved the IP address to a file
            echo "BACKEND_IP=${BACKEND_IP}"
      - run:
          name: Backend smoke test.
          command: |
            API_URL="http://${BACKEND_IP}:3030"
            echo "${API_URL}"
            if curl "${API_URL}/api/status" | grep "ok"
            then
              echo "Backend smoke test passed."
            else
              echo "Backend smoke test failed."
              exit 1
            fi
      - run:
          name: Frontend smoke test.
          command: |
            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"
            echo "${URL}"
            if curl -s "${URL}" | grep "Welcome"
            then
              echo "Frontend smoke test passed."
            else
              echo "Frontend smoke test failed."
              exit 1
            fi    


workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
          context: slack-credentials
      - scan-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
      - deploy-infrastructure:
          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
      - configure-infrastructure:
          requires: [deploy-infrastructure]
      - run-migrations:
          requires: [configure-infrastructure]
      - deploy-frontend:
          requires: [run-migrations]
      - deploy-backend:
          requires: [run-migrations]