version: 2.1
orbs:
  slack: circleci/slack@4.12.5

commands:
  destroy-environment:
    description: Destroy back-end and front-end CloudFormation stacks given a workflow ID.
    parameters:
      workflow-id:
        description: Workflow ID to identify the CloudFormation stacks.
        type: string
        default: "${CIRCLE_WORKFLOW_ID:0:7}"  # Default to first 7 characters of workflow ID
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |

            # Delete backend stack if it was created
            aws cloudformation delete-stack --stack-name udapeople-backend-<<parameters.workflow-id>>
            
            # Delete frontend stack if it was created
            aws cloudformation delete-stack --stack-name udapeople-frontend-<<parameters.workflow-id>>
            
            # Exit with a failure status
            exit 1


jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [test-frontend]
      - run:
          name: Test frontend
          command: |
            cd frontend
            npm install
            npm run test
  test-backend:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys: [test-backend]
      - run:
          name: Test backend
          command: |
            cd backend
            npm install
            npm run test
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
      - slack/notify:
          event: fail
          mentions: "@amit sharma"
          template: basic_fail_1

  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [scan-frontend]
      - run:
          name: Scan frontend
          command: |
            cd frontend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit fix --force
            npm audit --audit-level=critical

  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [scan-backend]
      - run:
          name: Scan backend
          command: |
            cd backend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit fix --force
            npm audit --audit-level=critical

  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli  # Replace with the Docker image that supports AWS CLI
    steps:
      - checkout  # Checkout code from Git
      - run:
          name: Install tar and gzip
          command: yum install -y tar gzip
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
              --tags project=udapeople
      - run:
          name: Ensure front-end infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
              --tags project=udapeople
      - run:
          name: Add back-end IP to Ansible inventory
          command: |
            # Fetch EC2 instance IP
            INSTANCE_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-*" --query "Reservations[].Instances[].PublicIpAddress" --output text)
            echo "[web]" > ~/inventory.txt
            echo "$INSTANCE_IP" >> ~/inventory.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - inventory.txt    
      # Destroy environment on failure
      - destroy-environment:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}

  configure-infrastructure:
    docker:
      - image: python:3.9.16 # Docker image that supports Ansible
    steps:
      - checkout  # Checkout code from git

      # Add SSH key fingerprint to the job
      - add_ssh_keys:
          fingerprints:
            - "ac:07:f1:f9:b4:90:b4:fe:28:89:52:98:1f:d4:2f:f0"

      # Attach workspace to the job
      - attach_workspace:
          at: ~/

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            # Install necessary dependencies
            apt-get update
            apt-get install -y tar gzip ansible awscli

      # Configure server
      - run:
          name: Configure server
          command: |
            # Run the Ansible playbook against the EC2 instance
            cat ~/inventory.txt
            pwd
            ls -la
            ansible-playbook -i ~/inventory.txt \
              --private-key ~/.ssh/id_rsa \  
              --user ubuntu \
              ./ansible/configure-server.yml

      # Destroy environment on failure
      - destroy-environment:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}


workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
          context: slack-credentials
      - scan-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
      - deploy-infrastructure:
          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
      - configure-infrastructure:
          requires: [deploy-infrastructure]